name: docs-ui - main - PR

on:
  workflow_dispatch: {}
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize', 'ready_for_review' ]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: make install && make build
